version: "3"
services:
  mysql:
    container_name: mysql-container
    image: mysql:8.0.28
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydb
  mysql_test:
    container_name: mysql-test-container
    image: mysql:8.0.28
    platform: linux/amd64
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydb
